### ISSUE TITLE
summation of all molecules remaining after filtering

### ISSUE THREAD

**Issue by gilzimmerman** [RespirationScan/issues#5]
Ability to search for molecule name and add all values for remaining molecules and treat as a single "molecule". For example, search "sulf" to show all molecules with sulfer content.

**Comment by tamarsh** [comment]
Well, unless I misunderstand this request, after implementing ticket #6, this search concept works exactly the same as you described in this ticket, however, if it's not then please clarify this issue in more details

**Comment by tamarsh** [comment]
The way to implement this with our current version of Power BI is by creating preset bookmarks, those bookmarks could be set by the end-user or by us if they could instruct us on the specific sets they're looking for, and based on our current presentation, however, I guess that a given bookmark will be based on a set of Molecule Type, Position and set of Molecule Name(s) that will be saved as a preset bookmark where the Patient ID will be selected by the end-user separately

**Comment by tamarsh** [comment]
I have amended [Hermes_v8](https://app.powerbi.com/groups/me/reports/02a28ff1-9ef4-436b-afb4-85e08381dbed/ReportSectiona73631991686655784e3?experience=power-bi&bookmarkGuid=Bookmark0976eb567407575b8610) , I have added four buttons [clear], [apply], and two sets, where in this case the concept has changed slightly as following, you first select your option and then you'll need to click Apply Set in order to update the graphs

**Comment by tamarsh** [comment]
Gil, FYI, I have added a new option to select from a "Molecule Preset" (new field), where currently there is a few set of option to choose from where they're all set externally on our database

**Comment by gilzimmerman** [comment]
after selecting a point in the top right graph, in any situation, points do not show on the retention times or spectra graph.

This only appears on my side.
Possible cause is a discrepancy in time zones.

**Comment by rs-tamar** [comment]
I have now pushed a new version related to this issue, where I  cloned Analytical Chemistry Research Tool MS1, in this version the data has been imported rather than "query directly" but restricted to the patient 608 only (due to the file size)
Please check this Power BI test project named "Testing discrepancy in time zones" and verified this situation, I am wondering if the same issue we hit last time with the Spectrum Graph

**Comment by rs-tamar** [comment]
The identified issue has been successfully resolved by making necessary amendments to the date/time columns in the relevant view (oldapp."new_pbi_Hermes_mv"). To achieve this, the relevant columns were converted using the following approach: "TimeCollectionStart" AT TIME ZONE 'UTC' as "TimeCollectionStart". Despite attempting to disable the "Time Intelligence" option under Power BI, it did not yield the desired outcome.

**Comment by rs-tamar** [comment]
Gil, I believe that this issue could be closed

**Comment by gilzimmerman** [comment]
This does in fact seem resolved after turning the data tables into import with #10. We'll check after merging it into dev.

**Comment by gilzimmerman** [comment]
Leaving this open. 

Note: I am merging dev into this branch 5-summation. 

need to have an option/button to select all after the search. Searching alone does not apply a filter. 


For example, select patient 608, tube 5. Search for "brom" in the molecule list. 
No molecules in the search result are selected, and correctly, molecules in the area of molecule detections graph still show all the molecules. 

We need "select all"/"deselect all" buttons for this function to be effective. Maybe even a rolling list where we can add and remove them?

**Comment by rs-tamar** [comment]
it seems that I managed to come up with some workaround, I agree it's not the most intuitive, but as much as I tested it, it's working, and the "trick" is working as follows,  at the first you need to select the "All" option in the Molecule Preset, you then in the Molecule Name select the first option "Select All" and now when you return and select any specific option such as "Acetone" from the Molecule Preset or alternative search from the Molecule name or from both places, you will end up with the full and relevant option selected if you think that behind the scene the full list is still selected then I can tell you that I did test it and this is not the case

**Comment by rs-tamar** [comment]
Further to our conversation, we agree to reuse the old search controller which has better control over the Molecole names list and doesn't require the select all option, in addition to this, I have also extended the resolution to 1920x1080 and rearranged the view and the object as well as setting the Spectrum graph columns into a wider columns size, please review this part carefully as I am not sure if this is the right option for this graph/data?

**Comment by gilzimmerman** [comment]
closed and merged
